---
- name: Install python-pip
  apt:
    name: python3-pip
    state: present

- name: Install Docker
  script: files/get_docker.sh 

- name: Install Docker Module for Python
  pip:
    name: docker-compose

- name: Clone GitHub repository 
  git:
    repo: https://github.com/deviantony/docker-elk
    dest: /etc/docker-elk
    clone: yes
    update: yes

- name: Setup elk-stack
  community.docker.docker_compose:
    project_src: /etc/docker-elk
    files: docker-compose.yml
    profiles: setup

- name: Deploy elk-stack
  community.docker.docker_compose:
    project_src: /etc/docker-elk
    files: docker-compose.yml
